# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import demo_pb2 as demo__pb2


class ModelPublisherStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.listenModels = channel.unary_stream(
        '/variamosgrpc.ModelPublisher/listenModels',
        request_serializer=demo__pb2.Empty.SerializeToString,
        response_deserializer=demo__pb2.Model.FromString,
        )
    self.pushModel = channel.unary_unary(
        '/variamosgrpc.ModelPublisher/pushModel',
        request_serializer=demo__pb2.Model.SerializeToString,
        response_deserializer=demo__pb2.Empty.FromString,
        )


class ModelPublisherServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def listenModels(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def pushModel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ModelPublisherServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'listenModels': grpc.unary_stream_rpc_method_handler(
          servicer.listenModels,
          request_deserializer=demo__pb2.Empty.FromString,
          response_serializer=demo__pb2.Model.SerializeToString,
      ),
      'pushModel': grpc.unary_unary_rpc_method_handler(
          servicer.pushModel,
          request_deserializer=demo__pb2.Model.FromString,
          response_serializer=demo__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'variamosgrpc.ModelPublisher', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
