# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='demo.proto',
  package='variamosgrpc',
  syntax='proto3',
  serialized_options=_b('\n\017com.variamos.ngP\001'),
  serialized_pb=_b('\n\ndemo.proto\x12\x0cvariamosgrpc\"\x07\n\x05\x45mpty\")\n\x05Model\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07\x63ounter\x18\x02 \x01(\x03\x32\x87\x01\n\x0eModelPublisher\x12<\n\x0clistenModels\x12\x13.variamosgrpc.Empty\x1a\x13.variamosgrpc.Model\"\x00\x30\x01\x12\x37\n\tpushModel\x12\x13.variamosgrpc.Model\x1a\x13.variamosgrpc.Empty\"\x00\x42\x13\n\x0f\x63om.variamos.ngP\x01\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='variamosgrpc.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=35,
)


_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='variamosgrpc.Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='variamosgrpc.Model.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='counter', full_name='variamosgrpc.Model.counter', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Model'] = _MODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'demo_pb2'
  # @@protoc_insertion_point(class_scope:variamosgrpc.Empty)
  ))
_sym_db.RegisterMessage(Empty)

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), dict(
  DESCRIPTOR = _MODEL,
  __module__ = 'demo_pb2'
  # @@protoc_insertion_point(class_scope:variamosgrpc.Model)
  ))
_sym_db.RegisterMessage(Model)


DESCRIPTOR._options = None

_MODELPUBLISHER = _descriptor.ServiceDescriptor(
  name='ModelPublisher',
  full_name='variamosgrpc.ModelPublisher',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=81,
  serialized_end=216,
  methods=[
  _descriptor.MethodDescriptor(
    name='listenModels',
    full_name='variamosgrpc.ModelPublisher.listenModels',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_MODEL,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='pushModel',
    full_name='variamosgrpc.ModelPublisher.pushModel',
    index=1,
    containing_service=None,
    input_type=_MODEL,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODELPUBLISHER)

DESCRIPTOR.services_by_name['ModelPublisher'] = _MODELPUBLISHER

# @@protoc_insertion_point(module_scope)
